[project]
name = "portfolio"
version = "0.1.0"
description = "Add a short description here"
authors = ["yhori <yhori991@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]

[dependencies]
python = ">=3.13.3,<3.14"
quarto = ">=1.7.31,<2"
polars = ">=1.30.0,<2"
plotly = ">=6.1.1,<7"
panel = ">=1.7.0,<2"
markdownify = ">=0.14.1,<0.15"
jupyterlab = ">=4.4.2,<5"
jupyter_bokeh = ">=4.0.5,<5"
nbformat = ">=5.10.4,<6"
python-kaleido = ">=0.2.1,<0.3"
requests = ">=2.32.3,<3"
tenacity = ">=9.1.2,<10"
boltons = ">=24.0.0,<25"
returns = ">=0.25.0,<0.26"
loguru = ">=0.7.3,<0.8"

[feature.dev.dependencies]
ipykernel = "*"

[environments]
default = { features = ["dev"], solve-group = "prod" }
prod = { features = [], solve-group = "prod" }
